USE [Teste]
GO

IF OBJECT_ID('dbo.P_CFOP_ICMS_IPI') IS NOT NULL
BEGIN
    DROP PROCEDURE dbo.P_CFOP_ICMS_IPI
    IF OBJECT_ID('dbo.P_CFOP_ICMS_IPI') IS NOT NULL
        PRINT '<<< FALHA APAGANDO A PROCEDURE dbo.P_CFOP_ICMS_IPI >>>'
    ELSE
        PRINT '<<< PROCEDURE dbo.P_CFOP_ICMS_IPI APAGADA >>>'
END
GO
CREATE PROCEDURE dbo.P_CFOP_ICMS_IPI
AS

    SET NOCOUNT ON;
	SELECT
		CONCAT_WS(' | ', Cfop, ISNULL(MAX(BaseIcms),0), ISNULL(MAX(ValorIcms),0), ISNULL(MAX(BaseIpi),0), ISNULL(MAX(ValorIpi),0)) AS CFOP_ICMS_IPI
	FROM NotaFiscalItem
	GROUP BY Cfop

RETURN
GO
GRANT EXECUTE ON dbo.P_CFOP_ICMS_IPI TO [public]
GO
IF OBJECT_ID('dbo.P_CFOP_ICMS_IPI') IS NOT NULL
    PRINT '<<< PROCEDURE dbo.P_CFOP_ICMS_IPI CRIADA >>>'
ELSE
    PRINT '<<< FALHA NA CRIACAO DA PROCEDURE dbo.P_CFOP_ICMS_IPI >>>'
GO
